# Generated by Django 5.1 on 2024-08-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_tag',
            field=models.ManyToManyField(related_name='projects', to='research_app.tagmodel'),
        ),
    ]
